---
- hosts: lamp
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp

  tasks:
  - name: Create user, domain and database
    import_tasks: tasks/hs_basis.yml

  #################################
  ## install requirements
  #################################
  - name: Install composer
    import_tasks: tasks/hs_composer.yml
  - name: Install lastest PHP
    import_tasks: tasks/hs_php8_buster.yml

  ##################################
  ## create directories
  ##################################
  - name: create directory var/log
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/log"
      state: directory

  ##################################
  ## configuration
  ##################################

  - name: upload the password for the mysql database
    become: yes
    template:
      src: "templates/my.cnf"
      dest: "/home/pacs/{{pac}}/users/{{user}}/.my.cnf"
      mode: "700"

  ########################
  ## setup the apache site
  ########################

  - name: drop htdocs-ssl .htaccess
    become: yes
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl/.htaccess"
       state: absent
  - name: upload .htaccess file
    become: yes
    template:
      src: "templates/htaccess"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/.htaccess"
  - name: upload php.ini
    become: yes
    template:
      src: "templates/php.ini"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/fastcgi-ssl"
